# Generated by Django 5.0.6 on 2024-07-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_check', '0002_alter_payment_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
